twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        '%kernel.project_dir%/bundles/MetaCloudify/OwnCloudBundle/src/Resources/views': MetaCloudifyOwnCloudBundle
        '%kernel.project_dir%/bundles/MetaCloudify/FtpBundle/src/Resources/views': MetaCloudifyFtpBundle
        '%kernel.project_dir%/bundles/MetaCloudify/HomeBundle/src/Resources/views': MetaCloudifyHomeBundle

when@test:
    twig:
        strict_variables: true
