twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        '%kernel.project_dir%/bundles/UEMC/OwnCloud/src/Resources/views': UEMCOwnCloudBundle
        '%kernel.project_dir%/bundles/UEMC/Ftp/src/Resources/views': UEMCFtpBundle
        '%kernel.project_dir%/bundles/UEMC/_home/src/Resources/views': UEMC_homeBundle

when@test:
    twig:
        strict_variables: true
