controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

metacloudify_core:
    # loads routes from the given routing file stored in some bundle
    resource: '@MetaCloudifyCoreBundle/src/Resources/config/routing.yaml'

metacloudify_onedrive:
    # loads routes from the given routing file stored in some bundle
    resource: '@MetaCloudifyOneDriveBundle/src/Resources/config/routing.yaml'

metacloudify_owncloud:
    # loads routes from the given routing file stored in some bundle
    resource: '@MetaCloudifyOwnCloudBundle/src/Resources/config/routing.yaml'

metacloudify_googledrive:
    # loads routes from the given routing file stored in some bundle
    resource: '@MetaCloudifyGoogleDriveBundle/src/Resources/config/routing.yaml'

metacloudify_ftp:
    # loads routes from the given routing file stored in some bundle
    resource: '@MetaCloudifyFtpBundle/src/Resources/config/routing.yaml'

metacloudify_Home:
    # loads routes from the given routing file stored in some bundle
    resource: '@MetaCloudifyHomeBundle/src/Resources/config/routing.yaml'
