controllers:
    resource: ../../src/Controller/
    type: annotation
kernel:
    resource: ../../src/Kernel.php
    type: annotation
metacloudify_corebundle:
    resource: '@MetaCloudifyCoreBundle/src/Resources/config/annotations.yaml'
metacloudify_onedrivebundle:
    resource: '@MetaCloudifyOneDriveBundle/src/Resources/config/annotations.yaml'
metacloudify_owncloudbundle:
    resource: '@MetaCloudifyOwnCloudBundle/src/Resources/config/annotations.yaml'
metacloudify_googledrivebundle:
    resource: '@MetaCloudifyGoogleDriveBundle/src/Resources/config/annotations.yaml'
metacloudify_ftpbundle:
    resource: '@MetaCloudifyFtpBundle/src/Resources/config/annotations.yaml'
metacloudify_homebundle:
    resource: '@MetaCloudifyHomeBundle/src/Resources/config/annotations.yaml'
