# src/MetaCloudify/_home/Resources/config/services.yaml

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  MetaCloudify\_home\:
    resource: '../../'

  MetaCloudify\_home\Controller\:
    resource: '../../Controller/'
    public: true

  # Configura la carpeta de los public (vistas, CSS, JS, imágenes, etc.)
  MetaCloudify\_home\Resources\:
    resource: '../'
    public: true
