services:
  MetaCloudify\Core\Service\CloudService:
    public: true
    autoconfigure: true
    autowire: true

  MetaCloudify\Core\Controller\CoreController:
    public: true
    autoconfigure: true
    autowire: true