#index:
#    path: /
#    controller: App\Controller\DefaultController::index


# DESCOMENTAR PARA PROD
#not_found:
#  path: /{catchall}
#  controller: MetaCloudify\Core\Controller\CoreController::notFound
#  requirements:
#    catchall: .*

#error_handler:
#   path: /error-handler
#   controller: MetaCloudify\Core\Controller\CoreController::frameworkError
