index:
    path: /
    controller: MetaCloudify\HomeBundle\Controller\HomeController::index


# DESCOMENTAR PARA PROD
#not_found:
#  path: /{catchall}
#  controller: MetaCloudify\CoreBundle\Controller\CoreController::notFound
#  requirements:
#    catchall: .*

#error_handler:
#   path: /error-handler
#   controller: MetaCloudify\CoreBundle\Controller\CoreController::frameworkError
