clientId: 'xxxxxxxxxxxxx'
clientSecret: 'xxxxxxxxxxxxxxxxxxxx'
redirectUriLogin: 'http://localhost/MetaCloudify/public/index.php/googledrive/login'
redirectUriLoginToken: 'http://localhost/MetaCloudify/public/index.php/googledrive/login/token'
scopes:
  - 'https://www.googleapis.com/auth/drive.appdata'
  - 'https://www.googleapis.com/auth/drive.appfolder'
  - 'https://www.googleapis.com/auth/drive.install'
  - 'https://www.googleapis.com/auth/drive.file'
  - 'https://www.googleapis.com/auth/drive.readonly'
  - 'https://www.googleapis.com/auth/drive'
  - 'https://www.googleapis.com/auth/userinfo.profile'
